# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import scratch_api.models
import scratch_api.storage


class Migration(migrations.Migration):

    dependencies = [
        ('scratch_api', '0002_production_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANTLRScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_score', models.IntegerField()),
                ('parallelism_score', models.IntegerField()),
                ('synchronization_score', models.IntegerField()),
                ('flow_control_score', models.IntegerField()),
                ('user_interactivity_score', models.IntegerField()),
                ('logical_thinking_score', models.IntegerField()),
                ('data_representation_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductionHint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_class',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='image',
            field=models.ImageField(null=True, storage=scratch_api.storage.OverwriteStorage(), upload_to=scratch_api.models.get_image_path),
        ),
        migrations.AddField(
            model_name='teacherscore',
            name='production_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scratch_api.Production'),
        ),
        migrations.AddField(
            model_name='productionhint',
            name='production_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scratch_api.Production'),
        ),
        migrations.AddField(
            model_name='antlrscore',
            name='production_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scratch_api.Production'),
        ),
    ]
