# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scratch_api', '0008_auto_20170725_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_second',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_school_2', to='scratch_api.School'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_class_second',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_class_2', to='scratch_api.Class'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_school', to='scratch_api.School'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_class',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_class', to='scratch_api.Class'),
        ),
    ]
