# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scratch_api', '0009_auto_20170725_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
