# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scratch_api', '0010_user_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antlrscore',
            name='production_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scratch_api.Production'),
        ),
        migrations.AlterField(
            model_name='production',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacherscore',
            name='production_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scratch_api.Production'),
        ),
    ]
