# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-30 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scratch_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(verbose_name='回合')),
                ('detail', jsonfield.fields.JSONField(verbose_name='具体内容')),
            ],
        ),
        migrations.CreateModel(
            name='MatchArrange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0, verbose_name='类型')),
                ('result', models.IntegerField(choices=[(-1, '左侧胜'), (0, '对战中'), (1, '右侧胜'), (2, '尚未开始')], default=2, verbose_name='结果')),
            ],
        ),
        migrations.CreateModel(
            name='MatchGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.IntegerField(default=1, verbose_name='场次')),
                ('kind', models.IntegerField(choices=[(-1, '左侧先手'), (1, '右侧先手')], default=-1, verbose_name='先后顺序')),
                ('code', models.CharField(blank=True, max_length=16, null=True, verbose_name='代码')),
                ('result', models.IntegerField(choices=[(-1, '左侧胜'), (0, '对战中'), (1, '右侧胜'), (2, '尚未开始')], default=2, verbose_name='结果')),
                ('arrange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_match.MatchArrange', verbose_name='对抗赛')),
            ],
        ),
        migrations.CreateModel(
            name='MatchProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(verbose_name='分组')),
                ('score', models.IntegerField(default=0, verbose_name='积分')),
                ('com_question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scratch_api.CompetitionQuestion', verbose_name='竞赛题目')),
                ('production', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scratch_api.Production', verbose_name='参赛作品')),
            ],
        ),
        migrations.AddField(
            model_name='matcharrange',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left', to='team_match.MatchProduction', verbose_name='左侧选手'),
        ),
        migrations.AddField(
            model_name='matcharrange',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right', to='team_match.MatchProduction', verbose_name='右侧选手'),
        ),
        migrations.AddField(
            model_name='gamedetail',
            name='match_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_match.MatchGame', verbose_name='对局id'),
        ),
        migrations.AddField(
            model_name='gamedetail',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_match.MatchProduction', verbose_name='执行者'),
        ),
        migrations.AlterUniqueTogether(
            name='matchproduction',
            unique_together=set([('production', 'com_question')]),
        ),
        migrations.AlterUniqueTogether(
            name='matchgame',
            unique_together=set([('arrange', 'game')]),
        ),
        migrations.AlterUniqueTogether(
            name='matcharrange',
            unique_together=set([('left', 'right', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='gamedetail',
            unique_together=set([('match_game', 'round')]),
        ),
    ]
