# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-30 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_match', '0002_auto_20181030_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchproduction',
            name='com_question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scratch_api.CompetitionQuestion', verbose_name='竞赛题目'),
        ),
        migrations.DeleteModel(
            name='Com',
        ),
    ]
