# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-25 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scratch_api', '0001_initial'),
        ('team_match', '0003_auto_20181030_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionForBattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_battle', models.IntegerField(choices=[(0, '其它'), (1, '五子棋')], default=0, verbose_name='作品的游戏类型')),
                ('production', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scratch_api.Production', verbose_name='作品')),
            ],
        ),
        migrations.AlterField(
            model_name='matchproduction',
            name='production',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='team_match.ProductionForBattle', verbose_name='参赛作品'),
        ),
        migrations.AlterUniqueTogether(
            name='productionforbattle',
            unique_together=set([('production',)]),
        ),
    ]
