# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-20 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_match', '0004_auto_20181225_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchgame',
            name='code',
        ),
        migrations.AlterField(
            model_name='matcharrange',
            name='type',
            field=models.IntegerField(choices=[(0, '小组赛'), (1, '第一轮淘汰赛')], default=0, verbose_name='类型'),
        ),
    ]
