# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_badges', '0004_auto_20171226_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeaward',
            name='image',
            field=models.ImageField(default='badges/badge.png', upload_to='badges/'),
        ),
    ]
