# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-05 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_badges', '0005_auto_20171228_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeaward',
            name='image',
            field=models.ImageField(default='badges/badge.gif', upload_to='badges/'),
        ),
    ]
